language: node_js

node_js:
- 12

env:
  global:
    secure: jCoNwlW6HlzBcgRnGsdYQCtxSv77iTMbZvEili1A7SIgZjT9rCeBSp+VcjR0yx6aw3J1A+ktBkryqk0mlE6dHpRNbw9va/NQnGhxydGuKQvq2obq9loBzWuJeQ+ZZM2XrOH16yOPC8v2KxxKTtqZi1JFqHB6E6dIgDVwFierg9gSl3ZCb2Ri+W+pZ3nVId8WNgHr/YWaarMaNCq+7+Zw8/DwEZ+KEEu99PpG2RSiyv5gCnHVP6CxUxg46JFjTnZMTt4xLJAwrxryorOH9JoClZbXkEqbtzIuTurGhiFHcNV0WiJEqiil0Ihbd7Qi4JruzdXDweAeRmib/OBp6DwADPkEYrx5TVseyrpJAKokqEhbNNRjN/yFDqf0ZA4pXBHcDtYmoVVElnbTK2nJSzUyNLbGbLlEy/H86N7cKTqXlm5wd8Z6Ol1Mr7kqWl4FZO+R0zG7vYDWPGzDE8oHEA+yDsC3GLLn4wbmYmG2thHZIMs18XdlG3wj6Tbc6tKsqAZyqHqsY4BVwxDj+YSSyE84BP/rFutQ0rh5jbPcjSQ8/dTOSxcDVSCzKMUMMUvRGaPYzN9TeKT+AUVcyQNhQGkOwaYKBJCxm/ADR+dGMtfC3qE2hObgOq6nvGolKiG2GfjdRN/VYLPfq7FU/BpsDQ15m0BPDZmaudDe06f2NBOqj88=
  matrix:
  - export BUILD_RT="(node x86)"
  - export BUILD_RT="(node x64)"
  - export BUILD_RT="(electron x86)"
  - export BUILD_RT="(electron x64)"

matrix:
  fast_finish: true

before_script:
- git config --global user.name "Eko Eryanto"
- git config --global user.email ekoeryanto@gmail.com

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  sudo apt-get -qq update; sudo apt-get -qq install g++-4.8; export CXX='g++-4.8';
  sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups imagemagick
  ghostscript; fi
- export JOBS=4
- export BUILD_ONLY=true 

script:
- export TARACH=$([[ "$TRAVIS_OS_NAME" == "linux" && "${BUILD_RT[1]}" == "x86" ]] && echo "x86" || echo "ia32")
- npx prebuild --all --force --strip --target ${BUILD_RT[0]} --arch $TARACH -u $UTO

git:
  depth: 1

branches:
  only:
  - release

os:
  - linux
  - windows
  - osx