language: node_js
node_js:
  - 12

env:
  global:
    - JOBS=4
    - BUILD_ONLY=true 

before_script:
- git config --global user.name "Eko Eryanto"
- git config --global user.email ekoeryanto@gmail.com

script:
  - npx prebuild-ci

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - g++-multilib
      - cups-ppdc 
      - libcups2-dev
      - cups