# appveyor file

# build version format
version: "{build}"

platform: x64

image: Visual Studio 2017

# Set a known clone folder
clone_folder: c:\p

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Eko Eryanto"
  - git config --global user.email ekoeryanto@gmail.com

environment: 
  UTO:
    secure: AA2zX0xeCPV5EgMld2KE8msF3xBOiiva546EWDGT8BFqkb/83qj/X3uHT0q9p29b

install:
  - ps: Install-Product node 12 x64
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - cmd: npm install
  - cmd: echo 'Building for node'
  - cmd: npm run prebuild -- -u %UTO%
  - cmd: echo 'Building for electron'
  - cmd: npm run prebuild -- -t electron -u %UTO%

test_script:
  - node --version
  - npm --version

build: off

artifacts:
  - path: 'prebuilds\**\*.tar.gz'

branches:
  only:
    - release

cache:
  - '%APPDATA%\npm-cache'