# appveyor file

# build version format
version: "{build}"

platform: x64

image: Visual Studio 2015

# Set a known clone folder
clone_folder: c:\projects\node-printer

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Ion Lupascu"
  - git config --global user.email ionlupascu@gmail.com

# what combinations to test
environment:
  matrix:
    # Node.js
    - nodejs_version: "0.10.48"
      msvs_toolset: 12
      msvs_version: 2013
    - nodejs_version: "0.12.18"
      msvs_toolset: 12
      msvs_version: 2013
    - nodejs_version: "4.9.1"
      msvs_toolset: 12
      msvs_version: 2013
    - nodejs_version: "5.9.1"
      msvs_toolset: 14
      msvs_version: 2015
    - nodejs_version: "6.17.1"
      msvs_toolset: 14
      msvs_version: 2015
    - nodejs_version: "8.16.1"
      msvs_toolset: 14
      msvs_version: 2015
    - nodejs_version: "10.16.0"
      msvs_toolset: 14
      msvs_version: 2015
    - nodejs_version: "11.15.0"
      msvs_toolset: 14
      msvs_version: 2015
    - nodejs_version: "12.10.0"
      msvs_toolset: 14
      msvs_version: 2015
      build_electron: "true"

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "0.10.48"
    - nodejs_version: "0.12.18"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node 12 x64
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - cmd: CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64
  - npm install -g node-gyp node-pre-gyp
  - npm install --build-from-source --msvs_version=$env:msvs_version

test_script:
  - node --version
  - npm --version

after_test:
  - node-gyp clean
  - ps: ./tools/buildWindows.ps1

build: off

artifacts:
  - path: 'build\stage\**\*.tar.gz'

branches:
  only:
    - master
