# appveyor file

# build version format
version: "{build}"

platform: x64

image: Visual Studio 2017

# Set a known clone folder
clone_folder: c:\p

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Eko Eryanto"
  - git config --global user.email ekoeryanto@gmail.com

environment: 
  UTO:
    secure: LCgKqXmOMGn//dRIygDqFdZY2SRk+sPWBX5rHxSWbO8ORW59m8PtxJu9hfq/fHEI

matrix:
  fast_finish: true

install:
  - ps: Install-Product node 12
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - cmd: npm ci --build-from-source
  - cmd: npx prebuild --strip -r electron -t 5.0.11 --arch x64
  - cmd: npx prebuild --strip -r electron -t 6.0.12 --arch x64
  - cmd: npx prebuild --strip -r node-webkit -t 0.37.4 --arch x64
  - cmd: npx prebuild --strip -r node-webkit -t 0.41.3 --arch x64
  - cmd: npx prebuild --strip -r node -t 12.12.0 --arch x64
  - cmd: npx prebuild --strip -r electron -t 5.0.11 --arch ia32
  - cmd: npx prebuild --strip -r electron -t 6.0.12 --arch ia32
  - cmd: npx prebuild --strip -r node-webkit -t 0.37.4 --arch ia32
  - cmd: npx prebuild --strip -r node-webkit -t 0.41.3 --arch ia32
  - cmd: npx prebuild --strip -r node -t 12.12.0 --arch ia32
  - cmd: npx prebuild -u %UTO%
test_script:
  - node --version
  - npm --version

build: off

branches:
  only:
    - release

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.node-gyp'